# Generated by Django 4.2.7 on 2025-08-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('yearly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code for charts', max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dashboard.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('query_type', models.CharField(max_length=100)),
                ('cached_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('query_parameters', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='dashboard_d_cache_k_80159c_idx'), models.Index(fields=['expires_at'], name='dashboard_d_expires_d6f0f7_idx'), models.Index(fields=['query_type'], name='dashboard_d_query_t_8a0b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('revenue', 'Total Revenue'), ('expenses', 'Total Expenses'), ('profit', 'Net Profit'), ('cash_flow', 'Cash Flow'), ('accounts_receivable', 'Accounts Receivable'), ('accounts_payable', 'Accounts Payable'), ('tax_liability', 'Tax Liability'), ('operating_expense', 'Operating Expenses'), ('other', 'Other')], max_length=30)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('calculation_method', models.TextField(blank=True, help_text='Description of how this metric was calculated')),
                ('data_sources', models.JSONField(default=list, help_text='List of data sources used for calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', 'metric_type'],
                'indexes': [models.Index(fields=['metric_type', 'period_type'], name='dashboard_f_metric__66ad57_idx'), models.Index(fields=['period_start', 'period_end'], name='dashboard_f_period__97927d_idx'), models.Index(fields=['created_at'], name='dashboard_f_created_0ef7b8_idx')],
                'unique_together': {('metric_type', 'period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('percentage_of_total', models.FloatField(help_text='Percentage of total expenses for the period')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='dashboard.expensecategory')),
            ],
            options={
                'ordering': ['-period_end', '-total_amount'],
                'indexes': [models.Index(fields=['category', 'period_start', 'period_end'], name='dashboard_e_categor_523e75_idx'), models.Index(fields=['period_start', 'period_end'], name='dashboard_e_period__59fc3e_idx')],
                'unique_together': {('category', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CashflowEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('inflow', 'Cash Inflow'), ('outflow', 'Cash Outflow')], max_length=20)),
                ('category', models.CharField(choices=[('operations', 'Operating Activities'), ('investing', 'Investing Activities'), ('financing', 'Financing Activities'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('source_document_id', models.UUIDField(blank=True, help_text='Reference to source document', null=True)),
                ('source_reconciliation_id', models.UUIDField(blank=True, help_text='Reference to reconciliation session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'transaction_type'], name='dashboard_c_date_2cdd81_idx'), models.Index(fields=['category'], name='dashboard_c_categor_52f0e8_idx'), models.Index(fields=['source_document_id'], name='dashboard_c_source__5b8c93_idx')],
            },
        ),
    ]
