# Generated by Django 4.2.7 on 2025-08-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=reports.models.report_upload_path)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('filters', models.JSONField(default=dict, help_text='Applied filters for report generation')),
                ('included_documents', models.JSONField(default=list, help_text='List of document IDs included')),
                ('included_reconciliations', models.JSONField(default=list, help_text='List of reconciliation session IDs')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_charts', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('audit_summary', 'Audit Summary Report'), ('reconciliation_report', 'Reconciliation Report'), ('financial_overview', 'Financial Overview'), ('cash_flow', 'Cash Flow Report'), ('expense_analysis', 'Expense Analysis'), ('compliance_report', 'Compliance Report'), ('custom', 'Custom Report')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_config', models.JSONField(default=dict, help_text='JSON configuration for report template')),
                ('include_charts', models.BooleanField(default=True)),
                ('chart_types', models.JSONField(default=list, help_text='List of chart types to include')),
                ('include_summary', models.BooleanField(default=True)),
                ('include_detailed_data', models.BooleanField(default=True)),
                ('include_exceptions', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=False)),
                ('header_color', models.CharField(default='#2E86AB', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('summary', 'Summary'), ('chart', 'Chart'), ('table', 'Table'), ('text', 'Text'), ('recommendations', 'Recommendations'), ('footer', 'Footer')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField(help_text='Section content data')),
                ('order', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(default=1)),
                ('style_config', models.JSONField(default=dict, help_text='Section-specific styling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.generatedreport')),
            ],
            options={
                'ordering': ['report', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='reports.generatedreport')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('donut', 'Donut Chart'), ('gauge', 'Gauge Chart')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(help_text='Chart data in JSON format')),
                ('chart_config', models.JSONField(default=dict, help_text='Chart configuration options')),
                ('width', models.IntegerField(default=600)),
                ('height', models.IntegerField(default=400)),
                ('chart_image', models.FileField(blank=True, null=True, upload_to='reports/charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='reports.reportsection')),
            ],
            options={
                'ordering': ['section', 'id'],
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['template_type'], name='reports_rep_templat_46c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_public', 'is_active'], name='reports_rep_is_publ_f73ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['report', 'order'], name='reports_rep_report__06852e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['section_type'], name='reports_rep_section_365278_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdownload',
            index=models.Index(fields=['report', 'downloaded_at'], name='reports_rep_report__9e5179_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdownload',
            index=models.Index(fields=['downloaded_by', 'downloaded_at'], name='reports_rep_downloa_342bed_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', 'created_at'], name='reports_gen_generat_4abf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status'], name='reports_gen_status_b3120a_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['template', 'created_at'], name='reports_gen_templat_b3931a_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['date_from', 'date_to'], name='reports_gen_date_fr_900ba6_idx'),
        ),
    ]
