# Generated by Django 4.2.7 on 2025-08-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('statement', 'Statement'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ocr', 'OCR Processing'), ('field_extraction', 'Field Extraction')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'job_type'], name='documents_p_documen_0257da_idx'), models.Index(fields=['status'], name='documents_p_status_e8fe8e_idx'), models.Index(fields=['task_id'], name='documents_p_task_id_e3ba77_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('date', 'Date'), ('amount', 'Amount'), ('vendor', 'Vendor'), ('description', 'Description'), ('invoice_number', 'Invoice Number'), ('tax_amount', 'Tax Amount'), ('currency', 'Currency'), ('payment_terms', 'Payment Terms'), ('due_date', 'Due Date'), ('other', 'Other')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('x_coordinate', models.IntegerField(blank=True, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='documents.document')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field_type', 'field_name'],
                'indexes': [models.Index(fields=['document', 'field_type'], name='documents_e_documen_c6d1d1_idx'), models.Index(fields=['field_type'], name='documents_e_field_t_af235c_idx'), models.Index(fields=['is_validated'], name='documents_e_is_vali_8db367_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='documents_d_uploade_28af31_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
    ]
