# Generated by Django 4.2.7 on 2025-08-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('viewer', 'Viewer'), ('admin', 'Administrator'), ('super_admin', 'Super Administrator')], default='client', max_length=20),
        ),
    ]
