# Generated by Django 4.2.7 on 2025-08-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_login', 'Suspicious Login'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('unusual_activity', 'Unusual Activity'), ('data_breach_attempt', 'Data Breach Attempt'), ('unauthorized_access', 'Unauthorized Access'), ('anomaly_transaction', 'Anomalous Transaction'), ('file_integrity_violation', 'File Integrity Violation'), ('session_hijacking', 'Session Hijacking'), ('account_created', 'Account Created')], max_length=30),
        ),
    ]
